{{- if not .Values.secrets.existingSecret }}
{{- if or .Values.secrets.grafanaApiKey .Values.secrets.redisPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podscope.secretName" . }}
  labels:
    {{- include "podscope.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.grafanaApiKey }}
  GRAFANA_API_KEY: {{ .Values.secrets.grafanaApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}
  {{- end }}
{{- end }}
{{- end }}
