{{- if .Values.tailscale.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "podscope.fullname" . }}-tailscale
  labels:
    {{- include "podscope.labels" . | nindent 4 }}
  annotations:
    tailscale.com/expose: "true"
    {{- if .Values.tailscale.hostname }}
    tailscale.com/hostname: {{ .Values.tailscale.hostname | quote }}
    {{- end }}
    {{- if .Values.tailscale.tags }}
    tailscale.com/tags: {{ .Values.tailscale.tags | quote }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "podscope.selectorLabels" . | nindent 4 }}
{{- end }}
